//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomPage.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomPage.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact us.
        /// </summary>
        public static string about_contact_us {
            get {
                return ResourceManager.GetString("about_contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string about_contact_us_address {
            get {
                return ResourceManager.GetString("about_contact_us_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments.
        /// </summary>
        public static string about_contact_us_comment_title {
            get {
                return ResourceManager.GetString("about_contact_us_comment_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string about_contact_us_email {
            get {
                return ResourceManager.GetString("about_contact_us_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string about_contact_us_phone {
            get {
                return ResourceManager.GetString("about_contact_us_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ARG Phone.
        /// </summary>
        public static string about_contact_us_phone_AR {
            get {
                return ResourceManager.GetString("about_contact_us_phone_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USA Toll Free.
        /// </summary>
        public static string about_contact_us_phone_USA {
            get {
                return ResourceManager.GetString("about_contact_us_phone_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direct Contact.
        /// </summary>
        public static string about_contact_us_title {
            get {
                return ResourceManager.GetString("about_contact_us_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specializations.
        /// </summary>
        public static string about_specializations {
            get {
                return ResourceManager.GetString("about_specializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coffee Types.
        /// </summary>
        public static string about_specializations_title {
            get {
                return ResourceManager.GetString("about_specializations_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Where are we?.
        /// </summary>
        public static string about_where_are_we {
            get {
                return ResourceManager.GetString("about_where_are_we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With a café on nearly every corner in countless cities around the globe, it comes as no surprise that coffee is one of the top commodities worldwide. As the global third most consumed beverage, after water and tea, coffee beans are in high demand everywhere. The top producing nations each produce millions of kilograms of coffee beans that find their way into the hands of eager consumers..
        /// </summary>
        public static string about_where_are_we_content {
            get {
                return ResourceManager.GetString("about_where_are_we_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Who we are?.
        /// </summary>
        public static string about_who_we_are {
            get {
                return ResourceManager.GetString("about_who_we_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We only buys from the most experienced and knowledgeable farmers because they produce the highest quality specialty beans. These coffees taste incredible, are tough to find but are worth the extra effort. We then dedicate a tremendous amount of time and energy to making sure every batch of coffee we roast meets or exceeds the standards we&apos;re looking for. To do this we cup and analyse every batch to figure out how to roast the next one even better. We use a combination of pretty amazing tools as well as our  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string about_who_we_are_content {
            get {
                return ResourceManager.GetString("about_who_we_are_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We are an award winning, small batch, specialty roaster. We are passionate about sustainably sourcing and roasting the world&apos;s best coffees and partnering with our customers to help them serve great coffees to theirs. We live and work in an amazing community and love the industry we work in. We&apos;ve begun to collect some pretty amazing awards and attention - which makes us work even harder!.
        /// </summary>
        public static string about_who_we_are_intro {
            get {
                return ResourceManager.GetString("about_who_we_are_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment.
        /// </summary>
        public static string contact_comment_attr {
            get {
                return ResourceManager.GetString("contact_comment_attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string contact_email_attr {
            get {
                return ResourceManager.GetString("contact_email_attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string contact_form_btn_submit {
            get {
                return ResourceManager.GetString("contact_form_btn_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter valid comment..
        /// </summary>
        public static string contact_form_comment_error {
            get {
                return ResourceManager.GetString("contact_form_comment_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max length of comment is 400 chars..
        /// </summary>
        public static string contact_form_comment_error_length {
            get {
                return ResourceManager.GetString("contact_form_comment_error_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter valid Email..
        /// </summary>
        public static string contact_form_email_error {
            get {
                return ResourceManager.GetString("contact_form_email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter valid Email..
        /// </summary>
        public static string contact_form_email_error_type {
            get {
                return ResourceManager.GetString("contact_form_email_error_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter valid lastname..
        /// </summary>
        public static string contact_form_lastname_error {
            get {
                return ResourceManager.GetString("contact_form_lastname_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max length of lastname is 50 chars..
        /// </summary>
        public static string contact_form_lastname_error_length {
            get {
                return ResourceManager.GetString("contact_form_lastname_error_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter valid name..
        /// </summary>
        public static string contact_form_name_error {
            get {
                return ResourceManager.GetString("contact_form_name_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max length of name is 50 chars..
        /// </summary>
        public static string contact_form_name_error_length {
            get {
                return ResourceManager.GetString("contact_form_name_error_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        public static string contact_lastname_attr {
            get {
                return ResourceManager.GetString("contact_lastname_attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string contact_name_attr {
            get {
                return ResourceManager.GetString("contact_name_attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string lang_eng {
            get {
                return ResourceManager.GetString("lang_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About us.
        /// </summary>
        public static string nav_AboutUs {
            get {
                return ResourceManager.GetString("nav_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        public static string nav_Contact {
            get {
                return ResourceManager.GetString("nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string nav_Home {
            get {
                return ResourceManager.GetString("nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks for your comment..
        /// </summary>
        public static string success_message {
            get {
                return ResourceManager.GetString("success_message", resourceCulture);
            }
        }
    }
}
